---
title: "Lab02"
output: html_document
---
```{r}
library(ggplot2)
library(tidyverse)
library(tidymodels)
library(corrplot)
library(ggthemes)
tidymodels_prefer()
```


```{r}
```


```{r}
abalone <- read_csv("~/Downloads/homework-2/data/abalone.csv")
```

```{r}
# Assess and describe the distribution of age.
abalone1 <- abalone %>%
  mutate(age = rings+1.5)
hist(abalone1$age)
#The distribution of age looks like a right skwed graph, with median around 12.
```

```{r}
# Question 2
#Split the abalone data into a training set and a testing set. Use stratified sampling. You should decide on appropriate percentages for splitting the data.

#Remember that you’ll need to set a seed at the beginning of the document to reproduce your results.
set.seed(6)

abalone_split <- initial_split(abalone1, prop = 0.80,
                                strata = age)
abalone_train <- training(abalone_split)
abalone_test <- testing(abalone_split)
```
```{r}
abalone_train1 <- abalone_train %>% mutate(type_I = if_else(type == "I", 1, 0)) %>%
  mutate(type_M = if_else(type == "M", 1, 0)) %>%select(-type)
```


```{r}
#Using the training data, create a recipe predicting the outcome variable, age, with all other predictor variables. Note that you should not include rings to predict age. Explain why you shouldn’t use rings to predict age.


#Steps for your recipe:
#dummy code any categorical predictors
abalone_recipe <- recipe(age ~ ., data = abalone_train1 %>% select(-rings)) %>% step_dummy(all_nominal_predictors()) %>%
  step_interact(~ longest_shell:diameter)  %>% 
  # shucked_weight and shell_weight
  step_interact(~ shucked_weight:shell_weight)  %>% 
  #type and shucked_weight
  step_interact(~ type_I:shell_weight + type_M:shell_weight)  %>% prep()%>%
  step_normalize(all_predictors())
summary(abalone_recipe)
```





```{r}
#Question 4
#Create and store a linear regression object using the "lm" engine.
lm_model1 <- linear_reg() %>% 
  set_engine("lm")
```
```{r}
#Question 5
#Now:
#set up an empty workflow,
#add the model you created in Question 4, and
#add the recipe that you created in Question 3.
lm_wflow1 <- workflow() %>% 
  add_model(lm_model1) %>% 
  add_recipe(abalone_recipe)
summary(abalone_recipe)
```
```{r}
#Question 6
#Use your fit() object to predict the age of a hypothetical female abalone with longest_shell = 0.50, diameter = 0.10, height = 0.30, whole_weight = 4, shucked_weight = 1, viscera_weight = 2, shell_weight = 1.
lm_fit1 <- fit(lm_wflow1, abalone_train1)
```

```{r}
example <- data.frame(longest_shell = 0.50, diameter = 0.10, height = 0.30, whole_weight = 4, shucked_weight = 1, viscera_weight = 2, shell_weight = 1, type_I = 0, type_M = 0)
abalone_train_example <- predict(lm_fit1, new_data = example)
abalone_train_example %>% 
  head()
```
```{r}
abalone_train_res <- predict(lm_fit1, new_data = abalone_train1)
abalone_train_res %>% 
  head()
```

```{r}
abalone_train_res <- bind_cols(abalone_train_res, abalone_train1 %>% select(age))
abalone_train_res %>% 
  head()
```

```{r}
rmse(abalone_train_res, truth = abalone_train1$age, estimate = .pred)
abalone_metrics <- metric_set(rmse, rsq, mae)
abalone_metrics(abalone_train_res, truth = age, 
                estimate = .pred)
```

